# Title: Gaza_infastructure_damage_Data_cleaning_script

## Introduction
Brief description of the dataset and objective of the cleaning process.

## Process

### Import libraries

In [ ]:
pip install ruff

Defaulting to user installation because normal site-packages is not writeable
Collecting ruff
  Downloading ruff-0.12.1-py3-none-win_amd64.whl.metadata (26 kB)
Downloading ruff-0.12.1-py3-none-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 349.5 kB/s eta 0:00:32
   - -------------------------------------- 0.5/11.5 MB 349.5 kB/s eta 0:00:32
   - -------------------------------------- 0.5/11.5 MB 349.5 kB/s eta 0:00:32
   - -------------------------------------- 0.5/11.5 MB 349.5 kB/s eta 0:00:32
   - -------------------------------------- 0.5/11.5 MB 349.5 kB/s eta 0:00:32
   - -------------------------------------- 0.5/11.5 MB 349.5 kB/s eta 0:00:32
   - -------------------------------------- 0.5/11.5 MB 349.5 kB/s eta 0:00:32
   -- ------------------------------------- 0.8/11.5 MB 238.0 kB/s eta 0:00:46
   -- ------------------------------------- 0.8/11.5 MB 238.0 kB/s eta 0:00:46
   -- ------------------------------------- 0.8/11.5 MB 238.0 kB/s eta 0:00:46
   -- ------------------------------------- 0.8/11.5 MB 238.0 kB/s eta 0:00:46
   -- ------------------------------------- 0.8/11.5 MB 238.0 kB/s eta 0:00:46
   -- ------------------------------------- 0.8/11.5 MB 238.0 kB/s eta 0:00:46
   -- ------------------------------------- 0.8/11.5 MB 238.0 kB/s eta 0:00:46
   -- ------------------------------------- 0.8/11.5 MB 238.0 kB/s eta 0:00:46
   --- ------------------------------------ 1.0/11.5 MB 200.6 kB/s eta 0:00:53
   --- ------------------------------------ 1.0/11.5 MB 200.6 kB/s eta 0:00:53
   --- ------------------------------------ 1.0/11.5 MB 200.6 kB/s eta 0:00:53
   --- ------------------------------------ 1.0/11.5 MB 200.6 kB/s eta 0:00:53
   --- ------------------------------------ 1.0/11.5 MB 200.6 kB/s eta 0:00:53
   --- ------------------------------------ 1.0/11.5 MB 200.6 kB/s eta 0:00:53
   --- ------------------------------------ 1.0/11.5 MB 200.6 kB/s eta 0:00:53
   ---- ----------------------------------- 1.3/11.5 MB 198.0 kB/s eta 0:00:52
   ---- ----------------------------------- 1.3/11.5 MB 198.0 kB/s eta 0:00:52
   ---- ----------------------------------- 1.3/11.5 MB 198.0 kB/s eta 0:00:52
   ---- ----------------------------------- 1.3/11.5 MB 198.0 kB/s eta 0:00:52
   ---- ----------------------------------- 1.3/11.5 MB 198.0 kB/s eta 0:00:52
   ----- ---------------------------------- 1.6/11.5 MB 203.1 kB/s eta 0:00:50
   ----- ---------------------------------- 1.6/11.5 MB 203.1 kB/s eta 0:00:50
   ----- ---------------------------------- 1.6/11.5 MB 203.1 kB/s eta 0:00:50
   ----- ---------------------------------- 1.6/11.5 MB 203.1 kB/s eta 0:00:50
   ----- ---------------------------------- 1.6/11.5 MB 203.1 kB/s eta 0:00:50
   ----- ---------------------------------- 1.6/11.5 MB 203.1 kB/s eta 0:00:50
   ------ --------------------------------- 1.8/11.5 MB 204.6 kB/s eta 0:00:48
   ------ --------------------------------- 1.8/11.5 MB 204.6 kB/s eta 0:00:48
   ------ --------------------------------- 1.8/11.5 MB 204.6 kB/s eta 0:00:48
   ------ --------------------------------- 1.8/11.5 MB 204.6 kB/s eta 0:00:48
   ------ --------------------------------- 1.8/11.5 MB 204.6 kB/s eta 0:00:48
   ------ --------------------------------- 1.8/11.5 MB 204.6 kB/s eta 0:00:48
   ------ --------------------------------- 1.8/11.5 MB 204.6 kB/s eta 0:00:48
   ------ --------------------------------- 1.8/11.5 MB 204.6 kB/s eta 0:00:48
   ------- -------------------------------- 2.1/11.5 MB 194.1 kB/s eta 0:00:49
   ------- -------------------------------- 2.1/11.5 MB 194.1 kB/s eta 0:00:49
   ------- -------------------------------- 2.1/11.5 MB 194.1 kB/s eta 0:00:49
   ------- -------------------------------- 2.1/11.5 MB 194.1 kB/s eta 0:00:49
   ------- -------------------------------- 2.1/11.5 MB 194.1 kB/s eta 0:00:49
   ------- -------------------------------- 2.1/11.5 MB 194.1 kB/s eta 0:00:49
   -------- ------------------------------- 2.4/11.5 MB 198.9 kB/s eta 0:00:47
   -------- ------------------------------- 2.4/11.5 MB 198.9 kB/s eta 0:00:47
   -------- ------------------------------- 2.4/11.5 MB 198.9 kB/s eta 0:00:47
   --------- ------------------------------ 2.6/11.5 MB 207.7 kB/s eta 0:00:43
   --------- ------------------------------ 2.6/11.5 MB 207.7 kB/s eta 0:00:43
   --------- ------------------------------ 2.6/11.5 MB 207.7 kB/s eta 0:00:43
   --------- ------------------------------ 2.6/11.5 MB 207.7 kB/s eta 0:00:43
   --------- ------------------------------ 2.6/11.5 MB 207.7 kB/s eta 0:00:43
   --------- ------------------------------ 2.6/11.5 MB 207.7 kB/s eta 0:00:43
   --------- ------------------------------ 2.9/11.5 MB 208.2 kB/s eta 0:00:42
   --------- ------------------------------ 2.9/11.5 MB 208.2 kB/s eta 0:00:42
   --------- ------------------------------ 2.9/11.5 MB 208.2 kB/s eta 0:00:42
   --------- ------------------------------ 2.9/11.5 MB 208.2 kB/s eta 0:00:42
   --------- ------------------------------ 2.9/11.5 MB 208.2 kB/s eta 0:00:42
   --------- ------------------------------ 2.9/11.5 MB 208.2 kB/s eta 0:00:42
   ---------- ----------------------------- 3.1/11.5 MB 210.9 kB/s eta 0:00:40
   ---------- ----------------------------- 3.1/11.5 MB 210.9 kB/s eta 0:00:40
   ---------- ----------------------------- 3.1/11.5 MB 210.9 kB/s eta 0:00:40
   ---------- ----------------------------- 3.1/11.5 MB 210.9 kB/s eta 0:00:40
   ----------- ---------------------------- 3.4/11.5 MB 215.8 kB/s eta 0:00:38
   ----------- ---------------------------- 3.4/11.5 MB 215.8 kB/s eta 0:00:38
   ----------- ---------------------------- 3.4/11.5 MB 215.8 kB/s eta 0:00:38
   ----------- ---------------------------- 3.4/11.5 MB 215.8 kB/s eta 0:00:38
   ----------- ---------------------------- 3.4/11.5 MB 215.8 kB/s eta 0:00:38
   ----------- ---------------------------- 3.4/11.5 MB 215.8 kB/s eta 0:00:38
   ------------ --------------------------- 3.7/11.5 MB 215.7 kB/s eta 0:00:37
   ------------ --------------------------- 3.7/11.5 MB 215.7 kB/s eta 0:00:37
   ------------ --------------------------- 3.7/11.5 MB 215.7 kB/s eta 0:00:37
   ------------ --------------------------- 3.7/11.5 MB 215.7 kB/s eta 0:00:37
   ------------- -------------------------- 3.9/11.5 MB 219.3 kB/s eta 0:00:35
   ------------- -------------------------- 3.9/11.5 MB 219.3 kB/s eta 0:00:35
   ------------- -------------------------- 3.9/11.5 MB 219.3 kB/s eta 0:00:35
   ------------- -------------------------- 3.9/11.5 MB 219.3 kB/s eta 0:00:35
   ------------- -------------------------- 3.9/11.5 MB 219.3 kB/s eta 0:00:35
   ------------- -------------------------- 3.9/11.5 MB 219.3 kB/s eta 0:00:35
   -------------- ------------------------- 4.2/11.5 MB 219.2 kB/s eta 0:00:34
   -------------- ------------------------- 4.2/11.5 MB 219.2 kB/s eta 0:00:34
   -------------- ------------------------- 4.2/11.5 MB 219.2 kB/s eta 0:00:34
   -------------- ------------------------- 4.2/11.5 MB 219.2 kB/s eta 0:00:34
   -------------- ------------------------- 4.2/11.5 MB 219.2 kB/s eta 0:00:34
   --------------- ------------------------ 4.5/11.5 MB 220.9 kB/s eta 0:00:33
   --------------- ------------------------ 4.5/11.5 MB 220.9 kB/s eta 0:00:33
   --------------- ------------------------ 4.5/11.5 MB 220.9 kB/s eta 0:00:33
   --------------- ------------------------ 4.5/11.5 MB 220.9 kB/s eta 0:00:33
   --------------- ------------------------ 4.5/11.5 MB 220.9 kB/s eta 0:00:33
   ---------------- ----------------------- 4.7/11.5 MB 222.8 kB/s eta 0:00:31
   ---------------- ----------------------- 4.7/11.5 MB 222.8 kB/s eta 0:00:31
   ---------------- ----------------------- 4.7/11.5 MB 222.8 kB/s eta 0:00:31
   ---------------- ----------------------- 4.7/11.5 MB 222.8 kB/s eta 0:00:31
   ---------------- ----------------------- 4.7/11.5 MB 222.8 kB/s eta 0:00:31
   ---------------- ----------------------- 4.7/11.5 MB 222.8 kB/s eta 0:00:31
   ----------------- ---------------------- 5.0/11.5 MB 222.4 kB/s eta 0:00:30
   ----------------- ---------------------- 5.0/11.5 MB 222.4 kB/s eta 0:00:30
   ----------------- ---------------------- 5.0/11.5 MB 222.4 kB/s eta 0:00:30
   ----------------- ---------------------- 5.0/11.5 MB 222.4 kB/s eta 0:00:30
   ------------------ --------------------- 5.2/11.5 MB 225.6 kB/s eta 0:00:28
   ------------------ --------------------- 5.2/11.5 MB 225.6 kB/s eta 0:00:28
   ------------------ --------------------- 5.2/11.5 MB 225.6 kB/s eta 0:00:28
   ------------------ --------------------- 5.2/11.5 MB 225.6 kB/s eta 0:00:28
   ------------------- -------------------- 5.5/11.5 MB 229.4 kB/s eta 0:00:27
   ------------------- -------------------- 5.5/11.5 MB 229.4 kB/s eta 0:00:27
   ------------------- -------------------- 5.5/11.5 MB 229.4 kB/s eta 0:00:27
   ------------------- -------------------- 5.5/11.5 MB 229.4 kB/s eta 0:00:27
   ------------------- -------------------- 5.8/11.5 MB 231.6 kB/s eta 0:00:25
   ------------------- -------------------- 5.8/11.5 MB 231.6 kB/s eta 0:00:25
   ------------------- -------------------- 5.8/11.5 MB 231.6 kB/s eta 0:00:25
   ------------------- -------------------- 5.8/11.5 MB 231.6 kB/s eta 0:00:25
   ------------------- -------------------- 5.8/11.5 MB 231.6 kB/s eta 0:00:25
   ------------------- -------------------- 5.8/11.5 MB 231.6 kB/s eta 0:00:25
   -------------------- ------------------- 6.0/11.5 MB 232.0 kB/s eta 0:00:24
   -------------------- ------------------- 6.0/11.5 MB 232.0 kB/s eta 0:00:24
   -------------------- ------------------- 6.0/11.5 MB 232.0 kB/s eta 0:00:24
   -------------------- ------------------- 6.0/11.5 MB 232.0 kB/s eta 0:00:24
   -------------------- ------------------- 6.0/11.5 MB 232.0 kB/s eta 0:00:24
   --------------------- ------------------ 6.3/11.5 MB 231.1 kB/s eta 0:00:23
   --------------------- ------------------ 6.3/11.5 MB 231.1 kB/s eta 0:00:23
   --------------------- ------------------ 6.3/11.5 MB 231.1 kB/s eta 0:00:23
   --------------------- ------------------ 6.3/11.5 MB 231.1 kB/s eta 0:00:23
   --------------------- ------------------ 6.3/11.5 MB 231.1 kB/s eta 0:00:23
   ---------------------- ----------------- 6.6/11.5 MB 232.1 kB/s eta 0:00:22
   ---------------------- ----------------- 6.6/11.5 MB 232.1 kB/s eta 0:00:22
   ---------------------- ----------------- 6.6/11.5 MB 232.1 kB/s eta 0:00:22
   ---------------------- ----------------- 6.6/11.5 MB 232.1 kB/s eta 0:00:22
   ---------------------- ----------------- 6.6/11.5 MB 232.1 kB/s eta 0:00:22
   ----------------------- ---------------- 6.8/11.5 MB 233.0 kB/s eta 0:00:21
   ----------------------- ---------------- 6.8/11.5 MB 233.0 kB/s eta 0:00:21
   ----------------------- ---------------- 6.8/11.5 MB 233.0 kB/s eta 0:00:21
   ----------------------- ---------------- 6.8/11.5 MB 233.0 kB/s eta 0:00:21
   ----------------------- ---------------- 6.8/11.5 MB 233.0 kB/s eta 0:00:21
   ------------------------ --------------- 7.1/11.5 MB 233.1 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 233.1 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 233.1 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 233.1 kB/s eta 0:00:20
   ------------------------- -------------- 7.3/11.5 MB 232.3 kB/s eta 0:00:19
   ------------------------- -------------- 7.3/11.5 MB 232.3 kB/s eta 0:00:19
   ------------------------- -------------- 7.3/11.5 MB 232.3 kB/s eta 0:00:19
   ------------------------- -------------- 7.3/11.5 MB 232.3 kB/s eta 0:00:19
   ------------------------- -------------- 7.3/11.5 MB 232.3 kB/s eta 0:00:19
   -------------------------- ------------- 7.6/11.5 MB 236.3 kB/s eta 0:00:17
   -------------------------- ------------- 7.6/11.5 MB 236.3 kB/s eta 0:00:17
   -------------------------- ------------- 7.6/11.5 MB 236.3 kB/s eta 0:00:17
   -------------------------- ------------- 7.6/11.5 MB 236.3 kB/s eta 0:00:17
   -------------------------- ------------- 7.6/11.5 MB 236.3 kB/s eta 0:00:17
   --------------------------- ------------ 7.9/11.5 MB 237.3 kB/s eta 0:00:16
   --------------------------- ------------ 7.9/11.5 MB 237.3 kB/s eta 0:00:16
   --------------------------- ------------ 7.9/11.5 MB 237.3 kB/s eta 0:00:16
   --------------------------- ------------ 7.9/11.5 MB 237.3 kB/s eta 0:00:16
   ---------------------------- ----------- 8.1/11.5 MB 244.1 kB/s eta 0:00:15
   ---------------------------- ----------- 8.1/11.5 MB 244.1 kB/s eta 0:00:15
   ---------------------------- ----------- 8.1/11.5 MB 244.1 kB/s eta 0:00:15
   ---------------------------- ----------- 8.1/11.5 MB 244.1 kB/s eta 0:00:15
   ----------------------------- ---------- 8.4/11.5 MB 246.1 kB/s eta 0:00:13
   ----------------------------- ---------- 8.4/11.5 MB 246.1 kB/s eta 0:00:13
   ----------------------------- ---------- 8.4/11.5 MB 246.1 kB/s eta 0:00:13
   ----------------------------- ---------- 8.4/11.5 MB 246.1 kB/s eta 0:00:13
   ----------------------------- ---------- 8.7/11.5 MB 250.4 kB/s eta 0:00:12
   ----------------------------- ---------- 8.7/11.5 MB 250.4 kB/s eta 0:00:12
   ----------------------------- ---------- 8.7/11.5 MB 250.4 kB/s eta 0:00:12
   ----------------------------- ---------- 8.7/11.5 MB 250.4 kB/s eta 0:00:12
   ----------------------------- ---------- 8.7/11.5 MB 250.4 kB/s eta 0:00:12
   ----------------------------- ---------- 8.7/11.5 MB 250.4 kB/s eta 0:00:12
   ------------------------------ --------- 8.9/11.5 MB 249.3 kB/s eta 0:00:11
   ------------------------------ --------- 8.9/11.5 MB 249.3 kB/s eta 0:00:11
   ------------------------------ --------- 8.9/11.5 MB 249.3 kB/s eta 0:00:11
   ------------------------------ --------- 8.9/11.5 MB 249.3 kB/s eta 0:00:11
   ------------------------------ --------- 8.9/11.5 MB 249.3 kB/s eta 0:00:11
   ------------------------------ --------- 8.9/11.5 MB 249.3 kB/s eta 0:00:11
   ------------------------------- -------- 9.2/11.5 MB 250.0 kB/s eta 0:00:10
   ------------------------------- -------- 9.2/11.5 MB 250.0 kB/s eta 0:00:10
   ------------------------------- -------- 9.2/11.5 MB 250.0 kB/s eta 0:00:10
   ------------------------------- -------- 9.2/11.5 MB 250.0 kB/s eta 0:00:10
   ------------------------------- -------- 9.2/11.5 MB 250.0 kB/s eta 0:00:10
   ------------------------------- -------- 9.2/11.5 MB 250.0 kB/s eta 0:00:10
   -------------------------------- ------- 9.4/11.5 MB 254.6 kB/s eta 0:00:09
   -------------------------------- ------- 9.4/11.5 MB 254.6 kB/s eta 0:00:09
   -------------------------------- ------- 9.4/11.5 MB 254.6 kB/s eta 0:00:09
   -------------------------------- ------- 9.4/11.5 MB 254.6 kB/s eta 0:00:09
   -------------------------------- ------- 9.4/11.5 MB 254.6 kB/s eta 0:00:09
   --------------------------------- ------ 9.7/11.5 MB 255.0 kB/s eta 0:00:08
   --------------------------------- ------ 9.7/11.5 MB 255.0 kB/s eta 0:00:08
   --------------------------------- ------ 9.7/11.5 MB 255.0 kB/s eta 0:00:08
   --------------------------------- ------ 9.7/11.5 MB 255.0 kB/s eta 0:00:08
   ---------------------------------- ----- 10.0/11.5 MB 255.8 kB/s eta 0:00:07
   ---------------------------------- ----- 10.0/11.5 MB 255.8 kB/s eta 0:00:07
   ---------------------------------- ----- 10.0/11.5 MB 255.8 kB/s eta 0:00:07
   ---------------------------------- ----- 10.0/11.5 MB 255.8 kB/s eta 0:00:07
   ---------------------------------- ----- 10.0/11.5 MB 255.8 kB/s eta 0:00:07
   ---------------------------------- ----- 10.0/11.5 MB 255.8 kB/s eta 0:00:07
   ---------------------------------- ----- 10.0/11.5 MB 255.8 kB/s eta 0:00:07
   ----------------------------------- ---- 10.2/11.5 MB 253.2 kB/s eta 0:00:06
   ----------------------------------- ---- 10.2/11.5 MB 253.2 kB/s eta 0:00:06
   ----------------------------------- ---- 10.2/11.5 MB 253.2 kB/s eta 0:00:06
   ----------------------------------- ---- 10.2/11.5 MB 253.2 kB/s eta 0:00:06
   ----------------------------------- ---- 10.2/11.5 MB 253.2 kB/s eta 0:00:06
   ------------------------------------ --- 10.5/11.5 MB 252.7 kB/s eta 0:00:05
   ------------------------------------ --- 10.5/11.5 MB 252.7 kB/s eta 0:00:05
   ------------------------------------ --- 10.5/11.5 MB 252.7 kB/s eta 0:00:05
   ------------------------------------ --- 10.5/11.5 MB 252.7 kB/s eta 0:00:05
   ------------------------------------ --- 10.5/11.5 MB 252.7 kB/s eta 0:00:05
   ------------------------------------- -- 10.7/11.5 MB 252.2 kB/s eta 0:00:04
   ------------------------------------- -- 10.7/11.5 MB 252.2 kB/s eta 0:00:04
   ------------------------------------- -- 10.7/11.5 MB 252.2 kB/s eta 0:00:04
   ------------------------------------- -- 10.7/11.5 MB 252.2 kB/s eta 0:00:04
   -------------------------------------- - 11.0/11.5 MB 253.4 kB/s eta 0:00:03
   -------------------------------------- - 11.0/11.5 MB 253.4 kB/s eta 0:00:03
   -------------------------------------- - 11.0/11.5 MB 253.4 kB/s eta 0:00:03
   -------------------------------------- - 11.0/11.5 MB 253.4 kB/s eta 0:00:03
   -------------------------------------- - 11.0/11.5 MB 253.4 kB/s eta 0:00:03
   -------------------------------------- - 11.0/11.5 MB 253.4 kB/s eta 0:00:03
   ---------------------------------------  11.3/11.5 MB 254.5 kB/s eta 0:00:02
   ---------------------------------------  11.3/11.5 MB 254.5 kB/s eta 0:00:02
   ---------------------------------------  11.3/11.5 MB 254.5 kB/s eta 0:00:02
   ---------------------------------------  11.3/11.5 MB 254.5 kB/s eta 0:00:02
   ---------------------------------------  11.3/11.5 MB 254.5 kB/s eta 0:00:02
   ---------------------------------------- 11.5/11.5 MB 254.4 kB/s eta 0:00:00
Installing collected packages: ruff
Successfully installed ruff-0.12.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
!pip install ydata-profiling

Requirement already satisfied: ydata-profiling in /usr/local/lib/python3.11/dist-packages (4.16.1)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.15.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.11.7)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.11/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.0.2)
Requirement already satisfied: htmlmin==0.1.12 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.4.4)
Requirement already satisfied: imagehash==4.3.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.9.4)
Requirement already satisfied: dacite>=1.8 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.11/dist-packages (from imagehash==4.3.1->ydata-profiling) (1.8.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from imagehash==4.3.1->ydata-profiling) (11.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.11/dist-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (4.14.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.6.15)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Requirement already satisfied: puremagic in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.29)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [ ]:
import pandas as pd  # noqa: F401
import numpy as np  # noqa: F401
import matplotlib.pyplot as plt  # noqa: F401
import seaborn as sns  # noqa: F401
from pandas_profiling import ProfileReport  # noqa: F401

/tmp/ipython-input-2-918478641.py:5: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport  # noqa: F401

### Load Data

In [ ]:
df = pd.read_json('data.json')
df.head()

,report_date,civic_buildings,educational_buildings,places_of_worship,residential
0,2023-10-07,{'ext_destroyed': 5},"{'ext_destroyed': 1, 'ext_damaged': 15}","{'ext_mosques_destroyed': 2, 'ext_mosques_dama...",{'ext_destroyed': 80}
1,2023-10-08,{'ext_destroyed': 11},"{'ext_destroyed': 1, 'ext_damaged': 30}","{'ext_mosques_destroyed': 4, 'ext_mosques_dama...","{'destroyed': 159, 'ext_destroyed': 159}"
2,2023-10-09,{'ext_destroyed': 16},"{'ext_destroyed': 2, 'ext_damaged': 45}","{'ext_mosques_destroyed': 6, 'ext_mosques_dama...","{'destroyed': 790, 'ext_destroyed': 790}"
3,2023-10-10,{'ext_destroyed': 22},"{'ext_destroyed': 2, 'ext_damaged': 60}","{'ext_mosques_destroyed': 8, 'ext_mosques_dama...","{'destroyed': 1009, 'ext_destroyed': 1009}"
4,2023-10-11,"{'destroyed': 27, 'ext_destroyed': 27}","{'destroyed': 3, 'ext_destroyed': 3, 'damaged'...","{'mosques_destroyed': 10, 'ext_mosques_destroy...","{'destroyed': 2835, 'ext_destroyed': 2835}"

#### First we need to convert the json format into csv

In [ ]:
data_frames = []
for idx, row in df.iterrows():
    civic_df = pd.json_normalize(row['civic_buildings'])
    educational_df = pd.json_normalize(row['educational_buildings'])
    places_of_worship_df = pd.json_normalize(row['places_of_worship'])
    residential_df = pd.json_normalize(row['residential'])

    data_frames.extend([civic_df, educational_df, places_of_worship_df, residential_df])

data = pd.concat(data_frames, ignore_index=True)
# data['report_date'] = df['report_date'].repeat(4).reset_index(drop=True)
data

,ext_destroyed,ext_damaged,ext_mosques_destroyed,ext_mosques_damaged,ext_churches_destroyed,destroyed,damaged,mosques_destroyed,mosques_damaged,churches_destroyed
0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,2.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN
3,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2315,210000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2316,225.0,NaN,NaN,NaN,NaN,225.0,NaN,NaN,NaN,NaN
2317,143.0,366.0,NaN,NaN,NaN,143.0,366.0,NaN,NaN,NaN
2318,NaN,NaN,828.0,NaN,3.0,NaN,NaN,828.0,NaN,3.0
2319,210000.0,NaN,NaN,NaN,NaN,210000.0,NaN,NaN,NaN,NaN

In [ ]:
data.shape

(2320, 10)

### Explore Data for missing values

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2320 entries, 0 to 2319
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ext_destroyed           1740 non-null   float64
 1   ext_damaged             580 non-null    float64
 2   ext_mosques_destroyed   580 non-null    float64
 3   ext_mosques_damaged     360 non-null    float64
 4   ext_churches_destroyed  580 non-null    float64
 5   destroyed               284 non-null    float64
 6   damaged                 92 non-null     float64
 7   mosques_destroyed       83 non-null     float64
 8   mosques_damaged         70 non-null     float64
 9   churches_destroyed      85 non-null     float64
dtypes: float64(10)
memory usage: 181.4 KB

### Handling Missing Values

In [ ]:
data.fillna(0, inplace= True)

### Handling Duplicates

In [ ]:
data.shape

(2320, 10)

In [ ]:
data[data.duplicated()]

,ext_destroyed,ext_damaged,ext_mosques_destroyed,ext_mosques_damaged,ext_churches_destroyed,destroyed,damaged,mosques_destroyed,mosques_damaged,churches_destroyed
21,3.0,75.0,0.0,0.0,0.0,3.0,75.0,0.0,0.0,0.0
124,80.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144,89.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
156,91.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
168,93.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
2312,224.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2313,142.0,364.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2314,0.0,0.0,828.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
2315,210000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2318,0.0,0.0,828.0,0.0,3.0,0.0,0.0,828.0,0.0,3.0

In [ ]:
replacement_dict = {
    'geo_precision': {1: 'City level', 2: 'District level', 3: 'Broad area'},
    'time_precision': {1: 'Exact date', 2: 'Approximate date', 3: 'Month only', 0: 'Unknown'}
}

df.replace(
    {
        ''
    }
)

### Handling Outliers

In [ ]:
Q1 = df["numeric_column"].quantile(0.25)
Q3 = df["numeric_column"].quantile(0.75)
IQR = Q3 - Q1
condition = ~(
    (df["numeric_column"] < (Q1 - 1.5 * IQR))
    | (df["numeric_column"] > (Q3 + 1.5 * IQR))
)
df = df[condition]

### Convert Data Types

### Feature Engineering

In [ ]:
df["new_feature"] = df["feature1"] / df["feature2"]

### Data Validation

In [ ]:
df["category_column"].unique()

### Save Cleaned Data

In [ ]:
df.to_csv("cleaned_dataset.csv", index=False)

# Summary and Next Steps
Summarize the cleaning process and outline next steps.