# Title: Gaza_infastructure_damage_Data_cleaning_script

## Introduction
Brief description of the dataset and objective of the cleaning process.

## Process

### Import libraries

In [1]:
%pip install ruff

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ruff in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.12.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install ydata-profiling

Defaulting to user installation because normal site-packages is not writeable
Collecting ydata-profiling
  Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting scipy<1.16,>=1.4.1 (from ydata-profiling)
  Downloading scipy-1.15.3-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from ydata-profiling) (2.2.3)
Collecting matplotlib<=3.10,>=3.5 (from ydata-profiling)
  Downloading matplotlib-3.10.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: pydantic>=2 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from ydata-profiling) (2.11.7)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting numpy<2.2,>=1.16.0 (from ydata-profiling)
  Downloading numpy-2.1.3-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: htmlmin==0.1.12 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from ydata-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from ydata-profiling) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.48.2 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Collecting statsmodels<1,>=0.13.2 (from ydata-profiling)
  Downloading statsmodels-0.14.4-cp312-cp312-win_amd64.whl.metadata (9.5 kB)
Collecting typeguard<5,>=3 (from ydata-profiling)
  Downloading typeguard-4.4.4-py3-none-any.whl.metadata (3.3 kB)
Collecting imagehash==4.3.1 (from ydata-profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Collecting wordcloud>=1.9.3 (from ydata-profiling)
  Downloading wordcloud-1.9.4-cp312-cp312-win_amd64.whl.metadata (3.5 kB)
Collecting dacite>=1.8 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Collecting numba<=0.61,>=0.56.0 (from ydata-profiling)
  Downloading numba-0.61.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: PyWavelets in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from imagehash==4.3.1->ydata-profiling) (1.8.0)
Requirement already satisfied: pillow in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from imagehash==4.3.1->ydata-profiling) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Collecting llvmlite<0.45,>=0.44.0dev0 (from numba<=0.61,>=0.56.0->ydata-profiling)
  Downloading llvmlite-0.44.0-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.4.26)
Collecting patsy>=0.5.6 (from statsmodels<1,>=0.13.2->ydata-profiling)
  Downloading patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: colorama in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tqdm<5,>=4.48.2->ydata-profiling) (0.4.6)
Collecting typing_extensions>=4.14.0 (from typeguard<5,>=3->ydata-profiling)
  Downloading typing_extensions-4.14.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: attrs>=19.3.0 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-1.29-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pydantic>=2->ydata-profiling) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pydantic>=2->ydata-profiling) (0.4.1)
Requirement already satisfied: six>=1.5 in c:\users\renter.tr-1000-004\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl (400 kB)
Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
Downloading matplotlib-3.10.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 365.1 kB/s eta 0:00:21
   --- ------------------------------------ 0.8/8.0 MB 479.7 kB/s eta 0:00:16
   --- ------------------------------------ 0.8/8.0 MB 479.7 kB/s eta 0:00:16
   --- ------------------------------------ 0.8/8.0 MB 479.7 kB/s eta 0:00:16
   ----- ---------------------------------- 1.0/8.0 MB 470.6 kB/s eta 0:00:15
   ----- ---------------------------------- 1.0/8.0 MB 470.6 kB/s eta 0:00:15
   ----- ---------------------------------- 1.0/8.0 MB 470.6 kB/s eta 0:00:15
   ------ --------------------------------- 1.3/8.0 MB 472.8 kB/s eta 0:00:15
   ------ --------------------------------- 1.3/8.0 MB 472.8 kB/s eta 0:00:15
   ------ --------------------------------- 1.3/8.0 MB 472.8 kB/s eta 0:00:15
   ------- -------------------------------- 1.6/8.0 MB 461.0 kB/s eta 0:00:15
   ------- -------------------------------- 1.6/8.0 MB 461.0 kB/s eta 0:00:15
   --------- ------------------------------ 1.8/8.0 MB 464.0 kB/s eta 0:00:14
   --------- ------------------------------ 1.8/8.0 MB 464.0 kB/s eta 0:00:14
   --------- ------------------------------ 1.8/8.0 MB 464.0 kB/s eta 0:00:14
   ---------- ----------------------------- 2.1/8.0 MB 466.1 kB/s eta 0:00:13
   ---------- ----------------------------- 2.1/8.0 MB 466.1 kB/s eta 0:00:13
   ---------- ----------------------------- 2.1/8.0 MB 466.1 kB/s eta 0:00:13
   ----------- ---------------------------- 2.4/8.0 MB 467.7 kB/s eta 0:00:13
   ----------- ---------------------------- 2.4/8.0 MB 467.7 kB/s eta 0:00:13
   ----------- ---------------------------- 2.4/8.0 MB 467.7 kB/s eta 0:00:13
   ------------- -------------------------- 2.6/8.0 MB 457.6 kB/s eta 0:00:12
   ------------- -------------------------- 2.6/8.0 MB 457.6 kB/s eta 0:00:12
   ------------- -------------------------- 2.6/8.0 MB 457.6 kB/s eta 0:00:12
   -------------- ------------------------- 2.9/8.0 MB 452.3 kB/s eta 0:00:12
   -------------- ------------------------- 2.9/8.0 MB 452.3 kB/s eta 0:00:12
   --------------- ------------------------ 3.1/8.0 MB 456.8 kB/s eta 0:00:11
   --------------- ------------------------ 3.1/8.0 MB 456.8 kB/s eta 0:00:11
   ---------------- ----------------------- 3.4/8.0 MB 462.9 kB/s eta 0:00:11
   ---------------- ----------------------- 3.4/8.0 MB 462.9 kB/s eta 0:00:11
   ---------------- ----------------------- 3.4/8.0 MB 462.9 kB/s eta 0:00:11
   ------------------ --------------------- 3.7/8.0 MB 471.1 kB/s eta 0:00:10
   ------------------ --------------------- 3.7/8.0 MB 471.1 kB/s eta 0:00:10
   ------------------ --------------------- 3.7/8.0 MB 471.1 kB/s eta 0:00:10
   ------------------- -------------------- 3.9/8.0 MB 467.9 kB/s eta 0:00:09
   ------------------- -------------------- 3.9/8.0 MB 467.9 kB/s eta 0:00:09
   -------------------- ------------------- 4.2/8.0 MB 470.4 kB/s eta 0:00:09
   -------------------- ------------------- 4.2/8.0 MB 470.4 kB/s eta 0:00:09
   -------------------- ------------------- 4.2/8.0 MB 470.4 kB/s eta 0:00:09
   ---------------------- ----------------- 4.5/8.0 MB 470.2 kB/s eta 0:00:08
   ---------------------- ----------------- 4.5/8.0 MB 470.2 kB/s eta 0:00:08
   ----------------------- ---------------- 4.7/8.0 MB 467.6 kB/s eta 0:00:08
   ----------------------- ---------------- 4.7/8.0 MB 467.6 kB/s eta 0:00:08
   ----------------------- ---------------- 4.7/8.0 MB 467.6 kB/s eta 0:00:08
   ------------------------ --------------- 5.0/8.0 MB 469.0 kB/s eta 0:00:07
   ------------------------ --------------- 5.0/8.0 MB 469.0 kB/s eta 0:00:07
   -------------------------- ------------- 5.2/8.0 MB 471.6 kB/s eta 0:00:06
   -------------------------- ------------- 5.2/8.0 MB 471.6 kB/s eta 0:00:06
   -------------------------- ------------- 5.2/8.0 MB 471.6 kB/s eta 0:00:06
   --------------------------- ------------ 5.5/8.0 MB 470.6 kB/s eta 0:00:06
   --------------------------- ------------ 5.5/8.0 MB 470.6 kB/s eta 0:00:06
   --------------------------- ------------ 5.5/8.0 MB 470.6 kB/s eta 0:00:06
   ---------------------------- ----------- 5.8/8.0 MB 469.8 kB/s eta 0:00:05
   ---------------------------- ----------- 5.8/8.0 MB 469.8 kB/s eta 0:00:05
   ----------------------------- ---------- 6.0/8.0 MB 472.0 kB/s eta 0:00:05
   ----------------------------- ---------- 6.0/8.0 MB 472.0 kB/s eta 0:00:05
   ----------------------------- ---------- 6.0/8.0 MB 472.0 kB/s eta 0:00:05
   ------------------------------- -------- 6.3/8.0 MB 468.9 kB/s eta 0:00:04
   ------------------------------- -------- 6.3/8.0 MB 468.9 kB/s eta 0:00:04
   ------------------------------- -------- 6.3/8.0 MB 468.9 kB/s eta 0:00:04
   -------------------------------- ------- 6.6/8.0 MB 468.2 kB/s eta 0:00:04
   -------------------------------- ------- 6.6/8.0 MB 468.2 kB/s eta 0:00:04
   -------------------------------- ------- 6.6/8.0 MB 468.2 kB/s eta 0:00:04
   --------------------------------- ------ 6.8/8.0 MB 468.6 kB/s eta 0:00:03
   --------------------------------- ------ 6.8/8.0 MB 468.6 kB/s eta 0:00:03
   ----------------------------------- ---- 7.1/8.0 MB 470.6 kB/s eta 0:00:03
   ----------------------------------- ---- 7.1/8.0 MB 470.6 kB/s eta 0:00:03
   ----------------------------------- ---- 7.1/8.0 MB 470.6 kB/s eta 0:00:03
   ------------------------------------ --- 7.3/8.0 MB 469.9 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.0 MB 469.9 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.0 MB 469.9 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.0 MB 468.8 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.0 MB 468.8 kB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 470.5 kB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 470.5 kB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 470.4 kB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading numba-0.61.0-cp312-cp312-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 430.4 kB/s eta 0:00:06
   ------- -------------------------------- 0.5/2.8 MB 430.4 kB/s eta 0:00:06
   ------- -------------------------------- 0.5/2.8 MB 430.4 kB/s eta 0:00:06
   ----------- ---------------------------- 0.8/2.8 MB 414.1 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 414.1 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.8 MB 414.1 kB/s eta 0:00:05
   -------------- ------------------------- 1.0/2.8 MB 419.4 kB/s eta 0:00:05
   -------------- ------------------------- 1.0/2.8 MB 419.4 kB/s eta 0:00:05
   -------------- ------------------------- 1.0/2.8 MB 419.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.3/2.8 MB 427.5 kB/s eta 0:00:04
   ------------------ --------------------- 1.3/2.8 MB 427.5 kB/s eta 0:00:04
   ------------------ --------------------- 1.3/2.8 MB 427.5 kB/s eta 0:00:04
   ---------------------- ----------------- 1.6/2.8 MB 432.4 kB/s eta 0:00:03
   ---------------------- ----------------- 1.6/2.8 MB 432.4 kB/s eta 0:00:03
   ------------------------- -------------- 1.8/2.8 MB 447.3 kB/s eta 0:00:03
   ------------------------- -------------- 1.8/2.8 MB 447.3 kB/s eta 0:00:03
   ----------------------------- ---------- 2.1/2.8 MB 462.3 kB/s eta 0:00:02
   ----------------------------- ---------- 2.1/2.8 MB 462.3 kB/s eta 0:00:02
   ----------------------------- ---------- 2.1/2.8 MB 462.3 kB/s eta 0:00:02
   --------------------------------- ------ 2.4/2.8 MB 464.4 kB/s eta 0:00:02
   --------------------------------- ------ 2.4/2.8 MB 464.4 kB/s eta 0:00:02
   --------------------------------- ------ 2.4/2.8 MB 464.4 kB/s eta 0:00:02
   ------------------------------------- -- 2.6/2.8 MB 450.8 kB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 450.8 kB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 450.8 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 442.6 kB/s eta 0:00:00
Downloading llvmlite-0.44.0-cp312-cp312-win_amd64.whl (30.3 MB)
   ---------------------------------------- 0.0/30.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/30.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/30.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/30.3 MB ? eta -:--:--

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Renter.TR-1000-004\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Renter.TR-1000-004\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\~umpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.8.1 which is incompatible.

In [72]:
import pandas as pd  # noqa: F401
import numpy as np  # noqa: F401
import matplotlib.pyplot as plt  # noqa: F401
import seaborn as sns  # noqa: F401
# from pandas_profiling import ProfileReport  # noqa: F401

### Load Data

In [152]:
import json

with open(
    "1_datasets/data/01_category_war_events_data/gaza_war_events/infrastructure_damaged/data.json"
) as file:
    json_data = json.load(file)
    data = pd.json_normalize(json_data)

In [116]:
data.shape

(580, 15)

In [153]:
data.columns

Index(['report_date', 'civic_buildings.ext_destroyed',
       'educational_buildings.ext_destroyed',
       'educational_buildings.ext_damaged',
       'places_of_worship.ext_mosques_destroyed',
       'places_of_worship.ext_mosques_damaged',
       'places_of_worship.ext_churches_destroyed', 'residential.ext_destroyed',
       'residential.destroyed', 'civic_buildings.destroyed',
       'educational_buildings.destroyed', 'educational_buildings.damaged',
       'places_of_worship.mosques_destroyed',
       'places_of_worship.mosques_damaged',
       'places_of_worship.churches_destroyed'],
      dtype='object')

As you see we need to rename the columns, acutally remove the prefix

In [158]:
data.rename(
    {
        "civic_buildings.ext_destroyed": "civic_ext_destroyed",
        "educational_buildings.ext_destroyed": "edu_ext_destroyed",
        "educational_buildings.ext_damaged": "edu_ext_damaged",
        "places_of_worship.ext_mosques_destroyed": "mosques_ext_destroyed",
        "places_of_worship.ext_mosques_damaged": "mosques_ext_damaged",
        "places_of_worship.ext_churches_destroyed": "churches_ext_destroyed",
        "residential.ext_destroyed": "residential_ext_destroyed",
        "residential.destroyed": "residential_destroyed",
        "civic_buildings.destroyed": "civic_destroyed",
        "educational_buildings.destroyed": "edu_destroyed",
        "educational_buildings.damaged": "edu_damaged",
        "places_of_worship.mosques_destroyed": "mosques_destroyed",
        "places_of_worship.mosques_damaged": "mosques_damaged",
        "places_of_worship.churches_destroyed": "churches_destroyed",
    },
    axis=1,
    inplace=True,
)

In [159]:
data.columns

Index(['report_date', 'civic_ext_destroyed', 'edu_ext_destroyed',
       'edu_ext_damaged', 'mosques_ext_destroyed', 'mosques_ext_damaged',
       'churches_ext_destroyed', 'residential_ext_destroyed',
       'residential_destroyed', 'civic_destroyed', 'edu_destroyed',
       'edu_damaged', 'mosques_destroyed', 'mosques_damaged',
       'churches_destroyed'],
      dtype='object')

### Explore Data for missing values

In [131]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 580 entries, 0 to 579
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   report_date             580 non-null    object
 1   ext_destroyed           580 non-null    int64
 2   ext_destroyed           580 non-null    int64
 3   ext_damaged             580 non-null    int64
 4   ext_mosques_destroyed   580 non-null    int64
 5   ext_mosques_damaged     360 non-null    float64
 6   ext_churches_destroyed  580 non-null    int64
 7   ext_destroyed           580 non-null    int64
 8   destroyed               108 non-null    float64
 9   destroyed               85 non-null     float64
 10  destroyed               91 non-null     float64
 11  damaged                 92 non-null     float64
 12  mosques_destroyed       83 non-null     float64
 13  mosques_damaged         70 non-null     float64
 14  churches_destroyed      85 non-null     float64
dtypes: float64(8), int64(6), object(1)
memory usage: 68.1+ KB

### Handling Missing Values

In [161]:
data.fillna(0, inplace=True)

### Handling Duplicates

In [133]:
data.shape

(580, 15)

In [134]:
data[data.duplicated()]

Empty DataFrame
Columns: [report_date, ext_destroyed, ext_destroyed, ext_damaged, ext_mosques_destroyed, ext_mosques_damaged, ext_churches_destroyed, ext_destroyed, destroyed, destroyed, destroyed, damaged, mosques_destroyed, mosques_damaged, churches_destroyed]
Index: []

### Convert Data Types

In [135]:
data.dtypes

report_date                object
ext_destroyed               int64
ext_destroyed               int64
ext_damaged                 int64
ext_mosques_destroyed       int64
ext_mosques_damaged       float64
ext_churches_destroyed      int64
ext_destroyed               int64
destroyed                 float64
destroyed                 float64
destroyed                 float64
damaged                   float64
mosques_destroyed         float64
mosques_damaged           float64
churches_destroyed        float64
dtype: object

In [137]:
data.head()

,report_date,ext_destroyed,ext_destroyed,ext_damaged,ext_mosques_destroyed,ext_mosques_damaged,ext_churches_destroyed,ext_destroyed,destroyed,destroyed,destroyed,damaged,mosques_destroyed,mosques_damaged,churches_destroyed
0,2023-10-07,5,1,15,2,4.0,0,80,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2023-10-08,11,1,30,4,8.0,0,159,159.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2023-10-09,16,2,45,6,12.0,0,790,790.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2023-10-10,22,2,60,8,17.0,0,1009,1009.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2023-10-11,27,3,75,10,21.0,0,2835,2835.0,27.0,3.0,75.0,10.0,0.0,0.0

In [162]:
data["report_date"] = pd.to_datetime(data["report_date"], errors="coerce")

### Save Cleaned Data

In [170]:
data.to_csv(
    "1_datasets/data/clean_datasets/infrastructure_damaged_clean.csv", index=False
)

# Summary and Next Steps
Summarize the cleaning process and outline next steps.